package event

type EventIDType int32

const (
	EVENT_ID_UNKNOWN EventIDType = iota
	EVENT_ID_COMPETITOR_REGISTERED
	EVENT_ID_START_TIME_SET_BY_DRAW
	EVENT_ID_COMPETITOR_ON_START_LINE
	EVENT_ID_COMPETITOR_STARTED
	EVENT_ID_COMPETITOR_ON_FIRING_RANGE
	EVENT_ID_TARGET_HIT
	EVENT_ID_COMPETITOR_LEFT_FIRING_RANGE
	EVENT_ID_COMPETITOR_ENTERED_PENALTY
	EVENT_ID_COMPETITOR_LEFT_PENALTY
	EVENT_ID_COMPETITOR_ENDED_MAIN_LAP
	EVENT_ID_COMPETITOR_CANNOT_CONTINUE
)

var EventIDToString = map[EventIDType]string{
	EVENT_ID_UNKNOWN:                      "UNKNOWN_EVENT",
	EVENT_ID_COMPETITOR_REGISTERED:        "COMPETITOR_REGISTERED (1)",
	EVENT_ID_START_TIME_SET_BY_DRAW:       "START_TIME_SET_BY_DRAW (2)",
	EVENT_ID_COMPETITOR_ON_START_LINE:     "COMPETITOR_ON_START_LINE (3)",
	EVENT_ID_COMPETITOR_STARTED:           "COMPETITOR_STARTED (4)",
	EVENT_ID_COMPETITOR_ON_FIRING_RANGE:   "COMPETITOR_ON_FIRING_RANGE (5)",
	EVENT_ID_TARGET_HIT:                   "TARGET_HIT (6)",
	EVENT_ID_COMPETITOR_LEFT_FIRING_RANGE: "COMPETITOR_LEFT_FIRING_RANGE (7)",
	EVENT_ID_COMPETITOR_ENTERED_PENALTY:   "COMPETITOR_ENTERED_PENALTY_LAPS (8)",
	EVENT_ID_COMPETITOR_LEFT_PENALTY:      "COMPETITOR_LEFT_PENALTY_LAPS (9)",
	EVENT_ID_COMPETITOR_ENDED_MAIN_LAP:    "COMPETITOR_ENDED_MAIN_LAP (10)",
	EVENT_ID_COMPETITOR_CANNOT_CONTINUE:   "COMPETITOR_CANNOT_CONTINUE (11)",
}
