package competitor

type CompetitorStatusType int

const (
	STATUS_UNKNOWN CompetitorStatusType = iota
	STATUS_NOT_REGISTERED
	STATUS_REGISTERED
	STATUS_ON_START_LINE
	STATUS_STARTED
	STATUS_ON_FIRING_RANGE
	STATUS_ON_PENALTY_LAP
	STATUS_FINISHED
	STATUS_NOT_FINISHED
	STATUS_NOT_STARTED
	STATUS_DISQUALIFIED
)

var competitorStatusToString = map[CompetitorStatusType]string{
	STATUS_UNKNOWN:         "STATUS_UNKNOWN",
	STATUS_NOT_REGISTERED:  "STATUS_NOT_REGISTERED",
	STATUS_REGISTERED:      "STATUS_REGISTERED",
	STATUS_ON_START_LINE:   "STATUS_ON_START_LINE",
	STATUS_STARTED:         "STATUS_STARTED",
	STATUS_ON_FIRING_RANGE: "STATUS_ON_FIRING_RANGE",
	STATUS_ON_PENALTY_LAP:  "STATUS_ON_PENALTY_LAP",
	STATUS_FINISHED:        "STATUS_FINISHED",
	STATUS_NOT_FINISHED:    "STATUS_NOT_FINISHED",
	STATUS_NOT_STARTED:     "STATUS_NOT_STARTED",
	STATUS_DISQUALIFIED:    "STATUS_DISQUALIFIED",
}
